### ISSUE TITLE
Does not build on kernel 5.15

### ISSUE THREAD

**Issue by Cyberunner23** [svpcom/rtl8812au#13]
The bulid fails with the following error

```
rtl8812au/core/rtw_br_ext.c:20:18: fatal error: netipx/ipx.h: No such file or directory
20 |         #include <net/ipx.h>
   |                  ^~~~~~~~~~~~~~
```

This is due to the ipx network layer being removed after being deprecated as mentioned [here](https://lkml.org/lkml/2021/8/13/334)

**Comment by svpcom** [comment]
@Cyberunner23 try a fix

**Comment by Cyberunner23** [comment]
It worked thanks!
