### ISSUE TITLE
Driver fails to build for 5.10.X kernel

### ISSUE THREAD

**Issue by justas-** [svpcom/rtl8812au#6]
Driver fails to build using 5.10.11 kernel. Worked fine with 5.4.79 version.

pi@raspberrypi:\~/rtl8812au $ make
make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.10.11-v7l+/build M=/home/pi/rtl8812au O="" modules
make[1]: Entering directory '/home/pi/kern/linux'
  CC [M]  /home/pi/rtl8812au/core/rtw_cmd.o
In file included from /home/pi/rtl8812au/include/drv_types.h:78,
                 from /home/pi/rtl8812au/core/rtw_cmd.c:17:
/home/pi/rtl8812au/include/rtw_security.h:246:8: error: redefinition of ‘struct sha256_state’
 struct sha256_state {
        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:24,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/pi/rtl8812au/include/osdep_service_linux.h:48,
                 from /home/pi/rtl8812au/include/osdep_service.h:51,
                 from /home/pi/rtl8812au/include/drv_types.h:27,
                 from /home/pi/rtl8812au/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
 struct sha256_state {
        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:279: /home/pi/rtl8812au/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1808: /home/pi/rtl8812au] Error 2
make[1]: Leaving directory '/home/pi/kern/linux'
make: *** [Makefile:1593: modules] Error 2
pi@raspberrypi:~/rtl8812au $ uname -a
Linux raspberrypi 5.10.11-v7l+ #1 SMP Wed Feb 3 09:30:08 GMT 2021 armv7l GNU/Linux

**Comment by svpcom** [comment]
Try branch v5.6.4.2

**Comment by svpcom** [comment]
@justas- Please report if this help or not

**Comment by justas-** [comment]
@svpcom  Compiled fine. Will test if works with wfb. This is a custom kernel build, as the stock RPi kernel does not have BPF enbled.

**Comment by justas-** [comment]
Loading module fails with:
Feb  3 19:31:08 raspberrypi kernel: [30019.091005] 88XXau: disagrees about version of symbol module_layout

Will retry building using dkms

EDIT:
After reboot driver is loaded and I get my rtl8812au interface up.

**Comment by justas-** [comment]
Building branch v5.6.4.2 fixed the issue.
